global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "relayx-services"
    static_configs:
      - targets:
          - "relayx-auth:8000"
          - "relayx-chat:8001"
          - "relayx-message-consumer:8002"
    metrics_path: "/metrics"
